[build]
ignore = "exit 1" #always build on PR even if you can't detect changes in this folder
publish = "public"
command = "npm install --legacy-peer-deps && hugo --minify && npx pagefind --site=public"
[dev]
framework = "hugo"
targetPort = 3000
command = "hugo server -p 3000"
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
[functions]
external_node_modules = ["node-fetch"]

[[headers]]
  for = "/dummy-apis/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
