[build]
publish = "public"
command = "npm install --legacy-peer-deps && hugo --minify && npx pagefind --source=public"
[dev]
framework = "hugo"
targetPort = 3000
command = "hugo server -p 3000"
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
[functions]
external_node_modules = ["node-fetch"]
