title = "The Launch"
baseURL = "https://launch.codeyourfuture.io/"

[module]
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/org-cyf-theme" 
  [[module.imports]]
    path = "github.com/CodeYourFuture/CYF-Projects/micro-front-end" 
    [[module.imports.mounts]]
      source = "content"
      target = "content/briefings"
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/org-cyf-guides" 
    [[module.imports.mounts]]
      source = "content"
      target = "content/guides"
  [[module.imports]]
    path = "github.com/CodeYourFuture/CYF-PD" 
    [[module.imports.mounts]]
      source = "content/blocks"
      target = "content/pd/blocks"


[markup]
# I've configured markdown so you don't have to
  [markup.tableOfContents]
    endLevel = 2
    ordered = true
    startLevel = 2
    [markup.goldmark.renderer]
# Enable HTML codeblocks, e.g. for <details> blocks
      unsafe = true