title = "The Launch"
baseURL = "https://launch.codeyourfuture.io/"

[module]
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/org-cyf-theme" 
  [[module.imports]]
    path = "github.com/CodeYourFuture/CYF-Projects/micro-front-end" 
    [[module.imports.mounts]]
      source = "content"
      target = "content/briefings"
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/org-cyf-guides" 
    [[module.imports.mounts]]
      source = "content"
      target = "content/guides"
  [[module.imports]]
    path = "github.com/CodeYourFuture/CYF-PD" 
    [[module.imports.mounts]]
      source = "content/blocks"
      target = "content/pd/blocks"


#this makes the section nav go the right way
# because of this 'unexpected behaviour' https://gohugo.io/methods/page/nextinsection/
[page]
  nextPrevInSectionSortOrder = 'asc'
  nextPrevSortOrder = 'asc'


[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = true
    startLevel = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
