backend:
  name: git-gateway
  branch: feature/cms
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
collections:
  - name: "employability"
    identifier_field: toml
    label: "Employability"
    folder: "content/employability"
    create: true
    path: "{{slug}}/index.md"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", const pattern = ['^.{1,55}$', 'Must have between 1 and 55 characters'], required: true }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: true,
        }
      - {
          label: "Emoji",
          name: "emoji",
          widget: "string",
          pattern: ['/\p{Emoji_Presentation}/gu', "Must be an emoji"],
          required: true,
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
