# This config is optimised for speed of local interation of general Hugo set-up without worrying about issue freshness or completeness.
# To build with this config, run `hugo server --environment issues-are-cached-and-incomplete`.

[params]
# Don't use the paginating proxy, because it's slow.
# This means some issues will be missing when fetched.
issuesorgapi = "https://api.github.com/repos/CodeYourFuture/"

[caches.getjson]
# Cache JSON responses because making fetches is slow when iterating.
# This means updates to issues (or newly created ones) won't be picked up when rebuilding.
maxAge = "4h"
