title = "MigraCode Barcelona"

[module]
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/common-theme" 
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/common-content" 
    [[module.imports.mounts]]
      source = "en"
      target = "content"
      

[params]
googleFonts="https://fonts.googleapis.com/css2?family=Jura:wght@300;400;700&display=swap"
description = "A free and open source software development programme."
main_website = "https://migracode.org/"
main_org_name = "MigraCode Barcelona"
our_name="MCB"
org = "https://github.com/Migracode-Barcelona"
repo = "https://github.com/CodeYourFuture/curriculum/org-mcb"
root = "curriculum"
orgapi = "https://api.github.com/repos/Migracode-Barcelona/"



[security.funcs]
# Allow accessing a GitHub bearer token to avoid rate limits when doing HTTP fetches to the GitHub API.
# This can be generated at https://github.com/settings/tokens?type=beta and needs read-only access to all public CYF GitHub repos.
getenv = ["^HUGO_CURRICULUM_GITHUB_BEARER_TOKEN$"]

[markup]
[markup.tableOfContents]
endLevel = 2
ordered = true
startLevel = 2
[markup.highlight]
lineNos = false
codeFences = true
guessSyntax = true
[markup.goldmark.renderer]
# Enable HTML codeblocks, e.g. for <details> blocks
unsafe = true
hardWraps = true
disableKinds = ["taxonomy", "term"]
footnote= true

theme = "common-theme"