backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: org-cyf-guides/static/img
public_folder: /img

collections:
  - name: "day_plans"
    label: "Day Plans"
    folder: "content/day-plans"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "day-plan",
        }
      - { label: "Emoji", name: "emoji", widget: "string" }
      - {
          label: "Menu Level",
          name: "menu_level",
          widget: "list",
          default: ["sprint"],
        }
      - { label: "Weight", name: "weight", widget: "number" }
      - {
          label: "No Register",
          name: "noRegister",
          widget: "boolean",
          default: false,
        }
      - label: "Blocks"
        name: "blocks"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Source", name: "src", widget: "string" }
          - { label: "Time", name: "time", widget: "number", required: false }
          - {
              label: "Caption",
              name: "caption",
              widget: "string",
              required: false,
            }

  - name: "prep"
    label: "Prep"
    folder: "content/prep"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "prep" }
      - { label: "Emoji", name: "emoji", widget: "string" }
      - {
          label: "Menu Level",
          name: "menu_level",
          widget: "list",
          default: ["sprint"],
        }
      - { label: "Weight", name: "weight", widget: "number" }
      - label: "Blocks"
        name: "blocks"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Source", name: "src", widget: "string" }
          - { label: "Time", name: "time", widget: "number", required: false }
          - {
              label: "Caption",
              name: "caption",
              widget: "string",
              required: false,
            }

  - name: "blocks"
    label: "Blocks"
    folder: "content/blocks"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Time", name: "time", widget: "number", default: 30 }
      - {
          label: "Hide from Overview",
          name: "hide_from_overview",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Threads",
          name: "threads",
          widget: "list",
          default: ["unassigned"],
        }
      - label: "Activities"
        name: "activities"
        widget: "relation"
        collection: "activities"
        searchFields: ["title"]
        valueField: "title"
        multiple: true
      - { label: "Emoji", name: "emoji", widget: "string", default: "🧩" }
      - label: "Objectives"
        name: "objectives"
        widget: "list"
        field: { label: "Objective", name: "objective", widget: "string" }
