name: Check consistency

on:
  pull_request:
  workflow_dispatch:

jobs:
  check_consistency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Build tooling
        run: (cd tooling/go && go build ./cmd/local-overrides-enforcer && go build ./cmd/sprint-consistency)
      - name: Check override consistency
        run: ./tooling/go/local-overrides-enforcer
      - name: Check sprint consistency
        # TODO: The Launch should probably have themes, but for now we'll ignore it so we can be checking the rest of the repo without having to fix this.
        run: ./tooling/go/sprint-consistency --exclude-roots org-cyf-launch
