name: Check consistency

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Build tooling
        run: (cd tooling/go && go build ./cmd/local-overrides-enforcer)
      - name: Check consistency
        run: ./tooling/go/local-overrides-enforcer
