on:
  schedule:
    - cron: '15 19 * * *'
  workflow_dispatch:
name: Nightly publish to Netlify

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish curriculum
      env:
        DEPLOY_HOOK_URL: ${{ secrets.CURRICULUM_NETLIFY_DEPLOY_HOOK_URL }}
      if: ${{ env.DEPLOY_HOOK_URL != '' }}
      run: curl --fail -X POST ${{ env.DEPLOY_HOOK_URL }}
    - name: Publish ITD
      env:
        DEPLOY_HOOK_URL: ${{ secrets.ITD_NETLIFY_DEPLOY_HOOK_URL }}
      if: ${{ env.DEPLOY_HOOK_URL != '' }}
      run: curl --fail -X POST ${{ env.DEPLOY_HOOK_URL }}
    - name: Publish ITP
      env:
        DEPLOY_HOOK_URL: ${{ secrets.ITP_NETLIFY_DEPLOY_HOOK_URL }}
      if: ${{ env.DEPLOY_HOOK_URL != '' }}
      run: curl --fail -X POST ${{ env.DEPLOY_HOOK_URL }}
    - name: Publish SDC
      env:
        DEPLOY_HOOK_URL: ${{ secrets.SDC_NETLIFY_DEPLOY_HOOK_URL }}
      if: ${{ env.DEPLOY_HOOK_URL != '' }}
      run: curl --fail -X POST ${{ env.DEPLOY_HOOK_URL }}
    - name: Publish Piscine
      env:
        DEPLOY_HOOK_URL: ${{ secrets.PISCINE_NETLIFY_DEPLOY_HOOK_URL }}
      if: ${{ env.DEPLOY_HOOK_URL != '' }}
      run: curl --fail -X POST ${{ env.DEPLOY_HOOK_URL }}
    - name: Publish Tracks
      env:
        DEPLOY_HOOK_URL: ${{ secrets.TRACKS_NETLIFY_DEPLOY_HOOK_URL }}
      if: ${{ env.DEPLOY_HOOK_URL != '' }}
      run: curl --fail -X POST ${{ env.DEPLOY_HOOK_URL }}
    - name: Publish Launch
      env:
        DEPLOY_HOOK_URL: ${{ secrets.LAUNCH_NETLIFY_DEPLOY_HOOK_URL }}
      if: ${{ env.DEPLOY_HOOK_URL != '' }}
      run: curl --fail -X POST ${{ env.DEPLOY_HOOK_URL }}
