on:
  schedule:
    - cron: '15 19 * * *'
  workflow_dispatch:
name: Nightly publish to Netlify

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish
      uses: netlify/actions/build@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
